### ISSUE TITLE
hello, I have performance problem

### ISSUE THREAD

**Issue by damody** [eclipse/paho.mqtt.rust#1]
I have 10000 machine,
each machine send message from mqtt every 10 sec,
so I want to use this library's asynchronous subscribe with multi-thread to figure it,
my problem is

https://github.com/eclipse/paho.mqtt.rust/blob/bccb73f44b43d6dc5896903e2d588b0a6841a8d7/examples/async_subscribe.rs#L93-L98

Could you show the callback multi-thread? thanks.

**Comment by fpagliughi** [comment]
I'm not exactly sure what you're asking.

The message callbacks all arrive on a single thread (which actually originates from the underlying C library). So that thread should certainly not be blocked for lengthy operations.

But the Message instance is completely owned by the callback, and can be passed on to other threads as needed. For example, if you give the callback a channel to another thread (or thread pool), you can simply send the message into the channel and let the other thread(s) process it:
```
tx_chan.send(msg).unrap();
```
Does that help?

**Comment by damody** [comment]
Thank you for giving me response, I try it.

**Comment by fpagliughi** [comment]
This would probably be a good thing to show in one of the sample apps. I’ll try to think up a somewhat realistic example and add it in over the next few days.

**Comment by damody** [comment]
thank you!
