### ISSUE TITLE
Paho mqtt-sn rust

### ISSUE THREAD

**Issue by asmakhalil** [eclipse/paho.mqtt.rust#149]
Hello!

I was wondering if this crate can be leveraged to provide a mqtt-sn Rust implementation. If not, were there any efforts underway to make a Rust crate for the paho.mqtt-sn.embedded-c library?

Thank you!

Asma

**Comment by fpagliughi** [comment]
Unfortunately, this crate just wraps the Paho C library which does all the actual networking communications. Since that library doesn't support MQTT-SN, than neither does this one. 

There has been some talk of more MQTT-SN support for Paho, and certainly it would be great to do it in Rust. For that matter, the goal for this library was always to move toward a 100% Rust implementation, and it  would be great to combine both goals, but it's unclear when there would be time for that without any funding.
