### ISSUE TITLE
Investigate safer alternative for C callbacks and providing AsyncClient as context.

### ISSUE THREAD

**Issue by jnicholls** [eclipse/paho.mqtt.rust#17]
In `set_message_callback` and `set_connection_lost_callback`, the call to `ffi::MQTTAsync_setCallbacks()` will pass a `self_ptr` ([see here](https://github.com/eclipse/paho.mqtt.rust/blob/master/src/async_client.rs#L715)), which is a pointer derived from the `&mut self` reference. This can yield undefined behavior when the `AsyncClient::on_message_arrived` callback is invoked and casts the context back to a `*mut AsyncClient`, because `&mut self` can be invalidated with simple code such as the following:

```
fn create_client(broker_url: &str, client_id: &str) -> AsyncClient {
    let mut client = AsyncClient::new((broker_url, client_id)).unwrap();
    client.set_message_callback(|_, _| {});
    client
}
```

What happens is the `AsyncClient` at the time of `set_message_callback` will be at one address location, but is then moved back to the caller who could then relocate AsyncClient somewhere else, e.g. inside of another data structure:

```
let client = create_client("tcp://localhost", "blah");
let state = MyState { client };
```

When a message arrives and that callback is invoked by the MQTT receive thread, the `self_ptr` has long since been invalidated. The only way to make it work properly is by boxing up the AsyncClient. For example:

```
fn create_client(broker_url: &str, client_id: &str) -> Box<AsyncClient> {
    let mut client = Box::new(AsyncClient::new((broker_url, client_id)).unwrap());
    client.set_message_callback(|_, _| {});
    client
}
```

would work fine, and the location of the AsyncClient in memory will remain in its allocated space on the heap.

I think there could be a safer approach to handling the callbacks, e.g. with allocated channels, rather than putting the burden on the user of AsyncClient to know how the callbacks work internally.

**Comment by fpagliughi** [comment]
Yeah, this problem of objects moving when copied/returned nailed me a couple times when I started the project!

I struggled with the implementation of the client, and certainly haven't gotten it right yet.

The issue is that, in many cases, the callback needs to access the client that generated it. The most common example is when the application is manually handling disconnect/reconnect functionality. When it receives a disconnect callback, it needs to tell the client to try to reconnect. So the callback needs to get some type of reference/pointer to the client.

An `Arc<Box<>>` seemed the proper thing, but I wasn't sure of how best to force that into the API without getting really ugly. A "trick" I've come across since then is to put the `Arc<Box<>>` into the struct, and then treat the client type itself like a reference. This was used in the [gpio-cdev crate](https://github.com/posborne/rust-gpio-cdev):

https://github.com/posborne/rust-gpio-cdev/blob/0bf05a9d1f63db02f693a1a8f5aaca26ed2af82b/src/lib.rs#L147-L149

I wasn't sure if the `Arc` was necessary. The callback obviously can't arrive from a client that has closed or been destroyed. But can the client disappear while the callback is running? I don't think so. But maybe the callback would want to pass a reference to the client to another thread?

Either way, though, you're right. This needs to be fixed.

**Comment by fpagliughi** [comment]
I reconsidered the use of an outer Arc<>, since leaking a raw Arc pointer to the C library would make it so that we couldn't close the client.

Using just a Box made the callbacks a bit hacky, since we temporarily create a second Box to the same address on the heap. But since we keep control of it just within the callbacks and don't expose the weirdness to the user, this should be OK.

Comments would be appreciated,
