### ISSUE TITLE
Documentation unclear on when do you get None in incoming messages.

### ISSUE THREAD

**Issue by mfrlin** [eclipse/paho.mqtt.rust#37]
Channel that you get from `start_consuming` can get either a message or `None`. In example there is a code that checks if client is disconnected: https://github.com/eclipse/paho.mqtt.rust/blob/c1f2de1a6e1ff12942eb4b5182d6029a84e01365/examples/sync_consume.rs#L118

This implies that you can get `None` because of something other than disconnect event. So my question is when do you get `None` and why do you need to check connected status of the client?

**Comment by fpagliughi** [comment]
At this point, that's still the only reason a _None_ comes through the pipe - if the client was disconnected. But I'm not sure that will always be true. I've been on the fence as whether to push a _None_ if there is an error processing the incoming message, or to knock the consumer off the stream if any other error occurs, in order to give the app the chance to fix things and then go back to reading.

So for now, you don't need to check, but in a future version you might.
