### ISSUE TITLE
Missing fields on build

### ISSUE THREAD

**Issue by gabisurita** [eclipse/paho.mqtt.rust#7]
Hi, I'm trying to build paho.mqtt.rust but I get a field missing error during compilation.

This error is against `paho.mqtt.c` master branch, but I also tried v1.2.x and develop with no success. What am I missing?

```
$ cargo test
   Compiling paho-mqtt3as-sys v0.2.0 (file:///Users/gusurita/paho.mqtt.rust/paho-mqtt3as-sys)                          
error[E0063]: missing fields `cleanstart`, `connectProperties`, `onFailure5` and 2 other fields in initializer of `MQTTAsync_connectOptions`
  --> paho-mqtt3as-sys/src/lib.rs:59:3
   |
59 |         MQTTAsync_connectOptions {
   |         ^^^^^^^^^^^^^^^^^^^^^^^^ missing `cleanstart`, `connectProperties`, `onFailure5` and 2 other fields

error[E0063]: missing fields `onFailure5`, `onSuccess5`, `properties` and 3 other fields in initializer of `MQTTAsync_responseOptions`
   --> paho-mqtt3as-sys/src/lib.rs:129:3
    |
129 |         MQTTAsync_responseOptions {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^ missing `onFailure5`, `onSuccess5`, `properties` and 3 other fields

error[E0063]: missing field `properties` in initializer of `MQTTAsync_message`
   --> paho-mqtt3as-sys/src/lib.rs:145:3
    |
145 |         MQTTAsync_message {
    |         ^^^^^^^^^^^^^^^^^ missing `properties`

error[E0063]: missing fields `onFailure5`, `onSuccess5`, `properties` and 1 other field in initializer of `MQTTAsync_disconnectOptions`
   --> paho-mqtt3as-sys/src/lib.rs:163:3
    |
163 |         MQTTAsync_disconnectOptions {
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `onFailure5`, `onSuccess5`, `properties` and 1 other field

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0063`.
```

**Comment by fpagliughi** [comment]
Apologies for the really slow response on this. For some reason I didn't receive notifications about several of these issues and pull requests. 

I probably should be more explicit in the README and build system that each Rust versions will likely be tied to a specific version version of the C library due to this problem - unless we can come up with some way around it...

The Paho C library often adds new functionality by growing the public structs that it uses, such as the `MQTTAsync_connectOptions`.  The C library adds new fields to the end of a struct and then bumps the `struct_version`. That then breaks the Rust wrapper, since Rust requires explicit initialization of each field. 

So, until this project moves to a 100% Rust implementation, each new release will likely target the latest official Paho C release, which is currently 1.2.1.

This will likely be handled automatically by having the Rust crate build (or at least verify) the specific C version, as we've been discussing in #3.

That all said, the Paho C lib is approaching a new release, so I need to get moving to have this version of Rust officially released, then move to get the new C version supported.

**Comment by fpagliughi** [comment]
To summarize, this version of the Rust crate targets Paho C v1.2.x (MQTT v3.1.1), while the next version will target Paho C 1.3 (MQTT v5).
