### ISSUE TITLE
Topic aliases

### ISSUE THREAD

**Issue by Tockra** [eclipse/paho.mqtt.rust#85]
Hi Guys,

I found the information that this crate supports mqtt v5. 
How can I enable it and how can I set the Topic aliases ( https://www.hivemq.com/blog/mqtt5-essentials-part10-topic-alias/ ) ? The publish method seems not to have a parameter.

I saw you have https://docs.rs/paho-mqtt/0.7.1/paho_mqtt/properties/enum.PropertyCode.html one enum which includes that flag. But I dont understand how and where to set this. 
The above link explains that the client give that information while Publish to the broker...

T

**Comment by fpagliughi** [comment]
Yes, I started looking at this to make an example, but it was a little tricky to do in the library since it's not a simple static configuration. It's at the top of my list for things to finish before the next release; to test and make it easy to use.

**Comment by Tockra** [comment]
Fortunately it's not important for me at the moment, but thank you for your work. Maybe in future I will need the feature ^^

**Comment by fpagliughi** [comment]
I added an example to the `develop` branch showing how to use topic aliases:
https://github.com/eclipse/paho.mqtt.rust/blob/develop/examples/topic_alias_publish.rs

It uses some new code in the `topic` struct which makes using aliases easy, but you can do it manually if you want. You need to do the following:

1. Create the client and connect using MQTT v5 parameter.
2. On connection complete, check the response for the `TopicAliasMaximum`. If it's missing or set to zero, then the server doesn't support topic aliases and you can not use them. Otherwise...
3. Send a normal message, with the topic name, but add the property `TopicAlias` with the alias value that you want to use. The value must be `1 <= alias <= TopicAliasMaximum`. This sets the alias on the server.
4. Send additional messages. These should use an empty topic name (""), but also have the `TopicAlias` property using the previously set alias value.

The alias(es) remain valid until the client is disconnected. (They must be reset on a reconnect if they're still desired).

**Comment by fpagliughi** [comment]
In v0.8
