### ISSUE TITLE
Futures support

### ISSUE THREAD

**Issue by jnicholls** [eclipse/paho.mqtt.rust#9]
For the `AsyncClient`, it would be cool if the `Token` implemented `Future`. I am going to be doing this myself—or at least attempt it—and if I pull it off I'll upstream it.

**Comment by jnicholls** [comment]
I guess one issue with this approach would be that the async operation is already in progress before `Future::poll` is called, so we're not really driving the completion of the action. In other words, if the returned `Token` never had `poll()` called on it, the operation would still be submitted to the C client.

The other problem is that `Token` is not `Send` which limits its usefulness as a `Future`. It kind of limits its usefulness entirely if I can only poll it from the same thread it was created. Fortunately I have a use case where I can make that work (an actix actor that issues an async mqtt command and returns a `Future` when the command has finished with its result). I think the `Future` work will need to be wrapped around the AsyncClient completely. In my case I'm going to do a custom `Future` but having a `FutureClient` that returns a `Future` rather than `Token`s would be cool. The returned `Future`s would not actually issue the calls to the AsyncClient until `poll()` was initially invoked. They could be alerted of their readiness via the C callback functions I suppose.

**Comment by fpagliughi** [comment]
I agree completely. The initial concept for this library was to bring MQTT programmers to Rust rather than the other way around (bringing Rust programmers to MQTT). Thus the idea was to have the Rust client mimic the other Paho API's (C++, Java, etc) and then evolve into better "Rustiness" over time. But it will be useless if it can't be integrated into a real Rust application. 

I've been taking my first baby steps into Rust Futures, and was looking to integrate this without straying too far from the existing API. An alternate client might be a way to go, if it doesn't get too confusing.

**Comment by fpagliughi** [comment]
It looks fairly trivial to implement the Future trait for the Token by replacing the condition variable with a task notification mechanism. I had some help on this from the Rust Forum:
https://users.rust-lang.org/t/futures-wrapping-an-async-c-library/23321

I'm going to create a "futures" branch and get on this immediately.

**Comment by fpagliughi** [comment]
Merged into the develop branch. Proceeding to release in v0.6/

**Comment by fpagliughi** [comment]
Tokens will also implement the _Send_ trait. See Issue #31 .
